// import './js/add-to-favorite';
import './js/current-page';
import './js/mobile-menu';
import './js/toggle-switcher-theme';
import './js/search-form';
import './js/formOpen';
import './js/formRegFatchData';
// import './js/to-favorite';
import './js/favorite-page';
import './js/btn-scroll-up';
