import './js/mobile-menu';
import './js/new-cards';
import './js/toggle-switcher-theme';
import './js/search-form';
import './js/API-service/api-weather';
import './js/current-page';
import './js/categories';
import './js/pagination';
import { initAccordion } from './js/accordion';
import { renderAccordion } from './js/render-ac-card';
import { readOnFormSubmit } from './js/render-ac-card';
